---
sudo: required

language: bash

script:
  - ./build_scripts/download-tf.sh
  - terraform init
  - terraform fmt -check=true

notifications:
  email:
    recipients:
      - yrochnyak@gmail.com
    on_success: change
    on_failure: change
