env:
- TF_VERSION=0.11.10

sudo: required

language: bash

before_install:
- wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip -O /tmp/terraform.zip
- sudo unzip -d /usr/local/bin/ /tmp/terraform.zip

script:
- terraform init
- terraform fmt -check=true
- terraform validate -check-variables=false

notifications:
  email:
    recipients:
    - yrochnyak@gmail.com
    on_success: change
    on_failure: change
